FROM logstash:2.1
MAINTAINER Matthias Endler <matthias-endler@gmx.net>

RUN apt-get update && apt-get install -y git rubygems python python-pip

# Install the logstash Kafka input plugin
RUN ./opt/logstash/bin/plugin install logstash-input-kafka

# Install the logstash InfluxDB output plugin
# Currently InfluxDB 0.9 support is not part of the official logstash influxdb plugin
# See https://github.com/logstash-plugins/logstash-output-influxdb/issues/24
# See https://github.com/logstash-plugins/logstash-output-influxdb/pull/29
# Therefore we add a fork for now which contains fixes for Influxdb 0.9
# and also allows us to set the InfluxDB measurement name from a field in the graphite string
RUN mkdir /logstash-plugins \
    && git clone https://github.com/ultramathman/logstash-output-influxdb.git /logstash-plugins/logstash-output-influxdb \
    && cd /logstash-plugins/logstash-output-influxdb/ \
    && gem build logstash-output-influxdb.gemspec \
    && /opt/logstash/bin/plugin install /logstash-plugins/logstash-output-influxdb/logstash-output-influxdb-2.0.2.gem

ADD contrib/logstash/config.conf /config/logstash-config.conf
ADD contrib/kafka-benchmark/config.py /kafka-benchmark/config.py

ADD run-logstash.sh run.sh
RUN chmod +x run.sh

CMD ["./run.sh"]
